resources:
- prometheus-service.yaml
- prometheus-daemonset.yaml
- prometheus-namespace.yaml
- simple-telemetry-deployment.yaml
- simple-telemetry-namespace.yaml
- simple-telemetry-service.yaml
- jaeger-namespace.yaml
- jaeger-service.yaml
- jaeger-statefulset.yaml
- fluent-bit-daemonset.yaml
- fluent-bit-namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: prometheus-config
  namespace: prometheus
  files:
  - prometheus.yaml
- name: simple-telemetry
  namespace: telemetry
  files:
  - simple-telemetry-publisher.yaml
- name: fluentbit-config
  namespace: fluentbit
  files:
  - fluent-bit.conf
  - fluent-bit-parsers.conf