apiVersion: v1
kind: Service
metadata:
  name: service-prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090