log:
  disable: false
  interval: 15s
  json-format: true
  extra-fields:
    foo: bar
metric:
  disable: false
  prometheus:
    port: 9004
    interval: 10s
trace:
  disable: false
  endpoint: "jaeger.jaeger.svc.cluster.local:4318"
  service-name: simple-publisher
  tracer-name: jaeger
  interval: 10s
graceful-shutdown: 5s