apiVersion: v1
kind: Service
metadata:
  name: simple-telemetry
  namespace: telemetry
  labels:
    app: simple-telemetry-publisher
spec:
  selector:
    app: simple-telemetry-publisher
  ports:
  - name: metrics
    protocol: TCP
    port: 9004
    targetPort: 9004